export type OverrideRow = {
  id: number;
  date: string;
  time_slot: string | null;
  is_closed: boolean;
  capacity_override: number | null;
  reason: string | null;
};

export type TicketFormState = {
  is_active: boolean;
  price: string;
  available_from: string;
  available_until: string;
  time_slots: string;
};

export type SettingsFormState = {
  max_tickets_per_booking: string;
  booking_window_days: string;
  auto_generate_days_ahead: string;
  default_slot_capacity: string;
};

export type OverrideFormState = {
  id: number | null;
  date: string;
  time_slot: string;
  is_closed: boolean;
  capacity_override: string;
  reason: string;
};

export type AvailabilityActionMode = 'generate' | 'regenerate';

export type ValidatedConfigValues = {
  normalizedTimeSlots: string[];
  price: number;
  maxTicketsPerBooking: number;
  bookingWindowDays: number;
  autoGenerateDaysAhead: number;
  defaultSlotCapacity: number;
};

export type ValidatedOverrideValues = {
  date: string;
  time_slot: string | null;
  is_closed: boolean;
  capacity_override: number | null;
  reason: string | null;
};
