import type { EntranceTicket } from '../../../hooks/useEntranceTicket';
import type { TicketBookingSettings } from '../../../hooks/useTicketBookingSettings';
import { parseRupiahInputValue } from '../../../utils/rupiahInput';
import type {
  OverrideFormState,
  SettingsFormState,
  TicketFormState,
  ValidatedConfigValues,
  ValidatedOverrideValues,
} from './entranceBookingTypes';

export function extractDateOnly(value: string | null | undefined) {
  return String(value ?? '').split('T')[0].split(' ')[0];
}

export function normalizeTimeSlotsInput(value: string): string[] {
  return value
    .split(',')
    .map((slot) => slot.trim())
    .filter(Boolean)
    .map((slot) => {
      const normalized = slot.length === 5 ? slot : slot.slice(0, 5);
      if (!/^\d{2}:\d{2}$/.test(normalized)) {
        throw new Error(`Invalid time slot "${slot}". Use HH:MM format.`);
      }
      return normalized;
    });
}

export function createTicketFormState(ticket: EntranceTicket): TicketFormState {
  return {
    is_active: ticket.is_active,
    price: parseRupiahInputValue(ticket.price),
    available_from: extractDateOnly(ticket.available_from),
    available_until: extractDateOnly(ticket.available_until),
    time_slots: ticket.time_slots.join(', '),
  };
}

export function createSettingsFormState(settings: TicketBookingSettings): SettingsFormState {
  return {
    max_tickets_per_booking: String(settings.max_tickets_per_booking),
    booking_window_days: String(settings.booking_window_days),
    auto_generate_days_ahead: String(settings.auto_generate_days_ahead),
    default_slot_capacity: String(settings.default_slot_capacity),
  };
}

export function createEmptyOverrideForm(): OverrideFormState {
  return {
    id: null,
    date: '',
    time_slot: '',
    is_closed: true,
    capacity_override: '',
    reason: '',
  };
}

export function validateConfigForms(
  ticketForm: TicketFormState,
  settingsForm: SettingsFormState
): ValidatedConfigValues {
  if (!ticketForm.available_from || !ticketForm.available_until) {
    throw new Error('Available from/until are required');
  }

  if (ticketForm.available_from > ticketForm.available_until) {
    throw new Error('Available from must be before available until');
  }

  const normalizedTimeSlots = normalizeTimeSlotsInput(ticketForm.time_slots);
  const normalizedPrice = parseRupiahInputValue(ticketForm.price);
  const price = Number(normalizedPrice);

  if (!normalizedPrice || !Number.isFinite(price) || price < 0) {
    throw new Error('Price must be a valid non-negative number');
  }

  const maxTicketsPerBooking = Number(settingsForm.max_tickets_per_booking);
  const bookingWindowDays = Number(settingsForm.booking_window_days);
  const autoGenerateDaysAhead = Number(settingsForm.auto_generate_days_ahead);
  const defaultSlotCapacity = Number(settingsForm.default_slot_capacity);

  if (
    !Number.isFinite(maxTicketsPerBooking) ||
    !Number.isFinite(bookingWindowDays) ||
    !Number.isFinite(autoGenerateDaysAhead) ||
    !Number.isFinite(defaultSlotCapacity) ||
    maxTicketsPerBooking <= 0 ||
    bookingWindowDays <= 0 ||
    autoGenerateDaysAhead < 0 ||
    defaultSlotCapacity <= 0
  ) {
    throw new Error('All operational settings must be valid positive numbers');
  }

  return {
    normalizedTimeSlots,
    price,
    maxTicketsPerBooking,
    bookingWindowDays,
    autoGenerateDaysAhead,
    defaultSlotCapacity,
  };
}

export function validateOverrideForm(form: OverrideFormState): ValidatedOverrideValues {
  if (!form.date) {
    throw new Error('Override date is required');
  }

  if (!form.is_closed && !form.capacity_override) {
    throw new Error('Set closed state or provide a capacity override');
  }

  const capacityOverride = form.capacity_override ? Number(form.capacity_override) : null;
  if (capacityOverride != null && (!Number.isFinite(capacityOverride) || capacityOverride <= 0)) {
    throw new Error('Capacity override must be a positive number');
  }

  return {
    date: form.date,
    time_slot: form.time_slot ? `${form.time_slot}:00` : null,
    is_closed: form.is_closed,
    capacity_override: capacityOverride,
    reason: form.reason.trim() || null,
  };
}
