import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../../../lib/supabase';
import type { EntranceTicket } from '../../../hooks/useEntranceTicket';
import type { TicketBookingSettings } from '../../../hooks/useTicketBookingSettings';
import { createSettingsFormState, createTicketFormState, validateConfigForms } from './entranceBookingHelpers';
import type { SettingsFormState, TicketFormState } from './entranceBookingTypes';

type UseEntranceBookingConfigFormArgs = {
  ticket: EntranceTicket | null | undefined;
  bookingSettings: TicketBookingSettings | null | undefined;
  refetchTicket: () => Promise<unknown>;
  refetchSettings: () => Promise<unknown>;
  showToast: (type: 'success' | 'error', message: string) => void;
};

export function useEntranceBookingConfigForm({
  ticket,
  bookingSettings,
  refetchTicket,
  refetchSettings,
  showToast,
}: UseEntranceBookingConfigFormArgs) {
  const [ticketForm, setTicketForm] = useState<TicketFormState | null>(null);
  const [settingsForm, setSettingsForm] = useState<SettingsFormState | null>(null);
  const [savingConfig, setSavingConfig] = useState(false);
  const hydratedTicketIdRef = useRef<number | null>(null);
  const hydratedTicketSnapshotRef = useRef<string | null>(null);
  const hydratedSettingsTicketIdRef = useRef<number | null>(null);
  const hydratedSettingsSnapshotRef = useRef<string | null>(null);

  useEffect(() => {
    if (!ticket) {
      hydratedTicketIdRef.current = null;
      hydratedTicketSnapshotRef.current = null;
      setTicketForm(null);
      return;
    }

    const nextForm = createTicketFormState(ticket);
    const nextSnapshot = JSON.stringify(nextForm);
    const previousTicketId = hydratedTicketIdRef.current;
    const previousSnapshot = hydratedTicketSnapshotRef.current;

    hydratedTicketIdRef.current = ticket.id;
    hydratedTicketSnapshotRef.current = nextSnapshot;
    setTicketForm((current) => {
      const shouldHydrate =
        previousTicketId !== ticket.id || current == null || JSON.stringify(current) === previousSnapshot;
      return shouldHydrate ? nextForm : current;
    });
  }, [ticket]);

  useEffect(() => {
    if (!bookingSettings) {
      hydratedSettingsTicketIdRef.current = null;
      hydratedSettingsSnapshotRef.current = null;
      setSettingsForm(null);
      return;
    }

    const nextForm = createSettingsFormState(bookingSettings);
    const nextSnapshot = JSON.stringify(nextForm);
    const previousTicketId = hydratedSettingsTicketIdRef.current;
    const previousSnapshot = hydratedSettingsSnapshotRef.current;

    hydratedSettingsTicketIdRef.current = bookingSettings.ticket_id;
    hydratedSettingsSnapshotRef.current = nextSnapshot;
    setSettingsForm((current) => {
      const shouldHydrate =
        previousTicketId !== bookingSettings.ticket_id || current == null || JSON.stringify(current) === previousSnapshot;
      return shouldHydrate ? nextForm : current;
    });
  }, [bookingSettings]);

  const hasConfigChanges = useMemo(() => {
    if (!ticketForm || !settingsForm) return false;
    return (
      JSON.stringify(ticketForm) !== hydratedTicketSnapshotRef.current ||
      JSON.stringify(settingsForm) !== hydratedSettingsSnapshotRef.current
    );
  }, [settingsForm, ticketForm]);

  const resetConfigForms = useCallback(() => {
    if (ticket) {
      setTicketForm(createTicketFormState(ticket));
    }
    if (bookingSettings) {
      setSettingsForm(createSettingsFormState(bookingSettings));
    }
  }, [bookingSettings, ticket]);

  const handleSaveConfig = useCallback(async () => {
    if (!ticket || !ticketForm || !settingsForm || savingConfig) return;

    try {
      const validated = validateConfigForms(ticketForm, settingsForm);
      setSavingConfig(true);

      const { error: saveError } = await supabase.rpc('save_entrance_booking_config', {
        p_ticket_id: ticket.id,
        p_is_active: ticketForm.is_active,
        p_price: validated.price,
        p_available_from: ticketForm.available_from,
        p_available_until: ticketForm.available_until,
        p_time_slots: validated.normalizedTimeSlots,
        p_max_tickets_per_booking: validated.maxTicketsPerBooking,
        p_booking_window_days: validated.bookingWindowDays,
        p_auto_generate_days_ahead: validated.autoGenerateDaysAhead,
        p_default_slot_capacity: validated.defaultSlotCapacity,
      });

      if (saveError) throw saveError;

      await Promise.all([refetchTicket(), refetchSettings()]);
      showToast('success', 'Entrance booking settings saved');
    } catch (error) {
      showToast('error', error instanceof Error ? error.message : 'Failed to save entrance booking settings');
    } finally {
      setSavingConfig(false);
    }
  }, [refetchSettings, refetchTicket, savingConfig, settingsForm, showToast, ticket, ticketForm]);

  return {
    ticketForm,
    setTicketForm,
    settingsForm,
    setSettingsForm,
    savingConfig,
    hasConfigChanges,
    resetConfigForms,
    handleSaveConfig,
  };
}
