-- Create rental orders table for dressing room rentals
-- This table stores rental orders with DOKU payment integration

create table if not exists public.rental_orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  look_id bigint, -- Reference to dressing_room_look if applicable
  duration_days integer not null,
  rental_start_time timestamp with time zone not null,
  rental_end_time timestamp with time zone not null,
  
  -- Customer data
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  customer_address text,
  
  -- Initial condition data
  initial_condition jsonb default '{}'::jsonb,
  
  -- Pricing
  subtotal numeric not null default 0,
  deposit_amount numeric not null default 0,
  total numeric not null default 0,
  
  -- Status
  status text not null default 'awaiting_payment' check (status in ('awaiting_payment', 'paid', 'active', 'overdue', 'returned', 'cancelled', 'refunded')),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'paid', 'failed', 'refunded')),
  
  -- Payment data
  payment_data jsonb default '{}'::jsonb,
  payment_url text,
  payment_expired_at timestamp with time zone,
  
  -- Return data (filled when returned)
  return_time timestamp with time zone,
  return_condition jsonb default '{}'::jsonb,
  late_fee_amount numeric default 0,
  damage_fee_amount numeric default 0,
  refund_amount numeric default 0,
  refund_processed boolean default false,
  
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Create rental order items table
create table if not exists public.rental_order_items (
  id bigint generated by default as identity primary key,
  rental_order_id bigint not null references public.rental_orders(id) on delete cascade,
  product_variant_id bigint not null references public.product_variants(id),
  product_name text not null,
  quantity integer not null default 1,
  daily_rate numeric not null,
  item_deposit_amount numeric not null,
  total_rental_cost numeric not null,
  
  -- Initial condition per item
  initial_condition jsonb default '{}'::jsonb,
  
  -- Return condition per item
  return_condition jsonb default '{}'::jsonb,
  
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Create indexes
create index if not exists idx_rental_orders_user_id on public.rental_orders(user_id);
create index if not exists idx_rental_orders_order_number on public.rental_orders(order_number);
create index if not exists idx_rental_orders_status on public.rental_orders(status);
create index if not exists idx_rental_orders_payment_status on public.rental_orders(payment_status);
create index if not exists idx_rental_order_items_rental_order_id on public.rental_order_items(rental_order_id);
create index if not exists idx_rental_order_items_product_variant_id on public.rental_order_items(product_variant_id);

-- Enable RLS
alter table public.rental_orders enable row level security;
alter table public.rental_order_items enable row level security;

-- RLS Policies for rental_orders
create policy "Users can view own rental orders" on public.rental_orders
  for select using (auth.uid() = user_id);

create policy "Users can insert own rental orders" on public.rental_orders
  for insert with check (auth.uid() = user_id);

create policy "Service role can manage all rental orders" on public.rental_orders
  for all using (auth.role() = 'service_role');

-- RLS Policies for rental_order_items
create policy "Users can view own rental order items" on public.rental_order_items
  for select using (
    exists (
      select 1 from public.rental_orders
      where rental_orders.id = rental_order_items.rental_order_id
      and rental_orders.user_id = auth.uid()
    )
  );

create policy "Users can insert own rental order items" on public.rental_order_items
  for insert with check (
    exists (
      select 1 from public.rental_orders
      where rental_orders.id = rental_order_items.rental_order_id
      and rental_orders.user_id = auth.uid()
    )
  );

create policy "Service role can manage all rental order items" on public.rental_order_items
  for all using (auth.role() = 'service_role');

-- Add comments
comment on table public.rental_orders is 'Rental orders for dressing room items with DOKU payment integration';
comment on table public.rental_order_items is 'Items in a rental order';
