CREATE TABLE IF NOT EXISTS public.ticket_booking_settings (
  ticket_id BIGINT PRIMARY KEY REFERENCES public.tickets(id) ON DELETE CASCADE,
  max_tickets_per_booking INTEGER NOT NULL DEFAULT 5 CHECK (max_tickets_per_booking > 0),
  booking_window_days INTEGER NOT NULL DEFAULT 30 CHECK (booking_window_days > 0),
  auto_generate_days_ahead INTEGER NOT NULL DEFAULT 60 CHECK (auto_generate_days_ahead >= 0),
  default_slot_capacity INTEGER NOT NULL DEFAULT 100 CHECK (default_slot_capacity > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO public.ticket_booking_settings (
  ticket_id,
  max_tickets_per_booking,
  booking_window_days,
  auto_generate_days_ahead,
  default_slot_capacity
)
SELECT
  t.id,
  5,
  30,
  CASE WHEN t.type = 'entrance' THEN 60 ELSE 0 END,
  100
FROM public.tickets t
WHERE NOT EXISTS (
  SELECT 1
  FROM public.ticket_booking_settings s
  WHERE s.ticket_id = t.id
);
CREATE TABLE IF NOT EXISTS public.ticket_availability_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  time_slot TIME NULL,
  is_closed BOOLEAN NOT NULL DEFAULT false,
  capacity_override INTEGER NULL CHECK (capacity_override > 0),
  reason TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ticket_availability_overrides_effective_change_check
    CHECK (is_closed = true OR capacity_override IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ticket_availability_overrides_date_unique
  ON public.ticket_availability_overrides (ticket_id, date)
  WHERE time_slot IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_ticket_availability_overrides_slot_unique
  ON public.ticket_availability_overrides (ticket_id, date, time_slot)
  WHERE time_slot IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ticket_availability_overrides_ticket_date
  ON public.ticket_availability_overrides (ticket_id, date);
CREATE OR REPLACE FUNCTION public.update_ticket_booking_settings_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trigger_ticket_booking_settings_updated_at ON public.ticket_booking_settings;
CREATE TRIGGER trigger_ticket_booking_settings_updated_at
  BEFORE UPDATE ON public.ticket_booking_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.update_ticket_booking_settings_updated_at();
CREATE OR REPLACE FUNCTION public.update_ticket_availability_overrides_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trigger_ticket_availability_overrides_updated_at ON public.ticket_availability_overrides;
CREATE TRIGGER trigger_ticket_availability_overrides_updated_at
  BEFORE UPDATE ON public.ticket_availability_overrides
  FOR EACH ROW
  EXECUTE FUNCTION public.update_ticket_availability_overrides_updated_at();
CREATE OR REPLACE FUNCTION public.enforce_ticket_availability_override_safety()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  conflicting_rows INTEGER := 0;
BEGIN
  SELECT COUNT(*)
  INTO conflicting_rows
  FROM public.ticket_availabilities ta
  WHERE ta.ticket_id = NEW.ticket_id
    AND ta.date = NEW.date
    AND (NEW.time_slot IS NULL OR ta.time_slot IS NOT DISTINCT FROM NEW.time_slot)
    AND (
      (NEW.is_closed = true AND (ta.reserved_capacity > 0 OR ta.sold_capacity > 0))
      OR (
        NEW.capacity_override IS NOT NULL
        AND NEW.capacity_override < (ta.reserved_capacity + ta.sold_capacity)
      )
    );

  IF conflicting_rows > 0 THEN
    RAISE EXCEPTION 'Override conflicts with sold or reserved capacity';
  END IF;

  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trigger_ticket_availability_overrides_safety ON public.ticket_availability_overrides;
CREATE TRIGGER trigger_ticket_availability_overrides_safety
  BEFORE INSERT OR UPDATE ON public.ticket_availability_overrides
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_ticket_availability_override_safety();
ALTER TABLE public.ticket_booking_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ticket_booking_settings FROM anon, authenticated;
GRANT SELECT ON public.ticket_booking_settings TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.ticket_booking_settings TO authenticated;
DROP POLICY IF EXISTS ticket_booking_settings_public_read ON public.ticket_booking_settings;
CREATE POLICY ticket_booking_settings_public_read
  ON public.ticket_booking_settings
  FOR SELECT
  TO anon, authenticated
  USING (true);
DROP POLICY IF EXISTS ticket_booking_settings_admin_full_access ON public.ticket_booking_settings;
CREATE POLICY ticket_booking_settings_admin_full_access
  ON public.ticket_booking_settings
  FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());
ALTER TABLE public.ticket_availability_overrides ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ticket_availability_overrides FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ticket_availability_overrides TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.ticket_availability_overrides_id_seq TO authenticated;
DROP POLICY IF EXISTS ticket_availability_overrides_admin_full_access ON public.ticket_availability_overrides;
CREATE POLICY ticket_availability_overrides_admin_full_access
  ON public.ticket_availability_overrides
  FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());
GRANT UPDATE ON public.tickets TO authenticated;
DROP POLICY IF EXISTS tickets_admin_update ON public.tickets;
CREATE POLICY tickets_admin_update
  ON public.tickets
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());
CREATE OR REPLACE FUNCTION public.list_ticket_time_slots(p_ticket_id BIGINT)
RETURNS TABLE (time_slot TIME)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT DISTINCT TRIM(slot.value)::TIME AS time_slot
  FROM public.tickets t
  CROSS JOIN LATERAL json_array_elements_text(COALESCE(t.time_slots, '[]'::json)) AS slot(value)
  WHERE t.id = p_ticket_id
    AND TRIM(slot.value) <> ''
  ORDER BY 1;
$$;
CREATE OR REPLACE FUNCTION public.list_effective_ticket_availabilities(
  p_ticket_id BIGINT,
  p_start_date DATE DEFAULT NULL,
  p_end_date DATE DEFAULT NULL
)
RETURNS TABLE (
  id BIGINT,
  ticket_id BIGINT,
  date DATE,
  time_slot TIME,
  base_total_capacity INTEGER,
  effective_total_capacity INTEGER,
  reserved_capacity INTEGER,
  sold_capacity INTEGER,
  available_capacity INTEGER,
  is_closed BOOLEAN,
  reason TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH slot_overrides AS (
    SELECT
      o.ticket_id,
      o.date,
      o.time_slot,
      o.is_closed,
      o.capacity_override,
      o.reason
    FROM public.ticket_availability_overrides o
    WHERE o.ticket_id = p_ticket_id
      AND o.time_slot IS NOT NULL
  ),
  date_level_overrides AS (
    SELECT
      o.ticket_id,
      o.date,
      o.is_closed,
      o.capacity_override,
      o.reason
    FROM public.ticket_availability_overrides o
    WHERE o.ticket_id = p_ticket_id
      AND o.time_slot IS NULL
  )
  SELECT
    ta.id,
    ta.ticket_id,
    ta.date,
    ta.time_slot,
    ta.total_capacity AS base_total_capacity,
    COALESCE(so.capacity_override, dlo.capacity_override, ta.total_capacity) AS effective_total_capacity,
    ta.reserved_capacity,
    ta.sold_capacity,
    CASE
      WHEN COALESCE(so.is_closed, dlo.is_closed, false) THEN 0
      ELSE GREATEST(
        COALESCE(so.capacity_override, dlo.capacity_override, ta.total_capacity) - ta.sold_capacity,
        0
      )
    END AS available_capacity,
    COALESCE(so.is_closed, dlo.is_closed, false) AS is_closed,
    COALESCE(so.reason, dlo.reason) AS reason
  FROM public.ticket_availabilities ta
  LEFT JOIN slot_overrides so
    ON so.ticket_id = ta.ticket_id
   AND so.date = ta.date
   AND so.time_slot = ta.time_slot
  LEFT JOIN date_level_overrides dlo
    ON dlo.ticket_id = ta.ticket_id
   AND dlo.date = ta.date
  WHERE ta.ticket_id = p_ticket_id
    AND (p_start_date IS NULL OR ta.date >= p_start_date)
    AND (p_end_date IS NULL OR ta.date <= p_end_date)
  ORDER BY ta.date ASC, ta.time_slot ASC;
$$;
GRANT EXECUTE ON FUNCTION public.list_ticket_time_slots(BIGINT) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.list_effective_ticket_availabilities(BIGINT, DATE, DATE) TO anon, authenticated, service_role;
CREATE OR REPLACE FUNCTION public.generate_ticket_availability(
  p_start_date DATE,
  p_end_date DATE,
  p_ticket_id BIGINT DEFAULT 1,
  p_total_capacity INTEGER DEFAULT NULL
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inserted_count INTEGER := 0;
  effective_start_date DATE;
  effective_end_date DATE;
  configured_capacity INTEGER;
  slot_count INTEGER;
BEGIN
  IF p_start_date IS NULL OR p_end_date IS NULL THEN
    RAISE EXCEPTION 'Start date and end date are required';
  END IF;

  IF p_start_date > p_end_date THEN
    RAISE EXCEPTION 'Start date must be before or equal to end date';
  END IF;

  IF auth.uid() IS NOT NULL AND NOT public.is_admin() THEN
    RAISE EXCEPTION 'Only admins can generate ticket availability';
  END IF;

  SELECT
    GREATEST(p_start_date, t.available_from::DATE),
    LEAST(p_end_date, t.available_until::DATE),
    COALESCE(p_total_capacity, s.default_slot_capacity)
  INTO
    effective_start_date,
    effective_end_date,
    configured_capacity
  FROM public.tickets t
  JOIN public.ticket_booking_settings s ON s.ticket_id = t.id
  WHERE t.id = p_ticket_id;

  IF effective_start_date IS NULL OR effective_end_date IS NULL OR effective_start_date > effective_end_date THEN
    RETURN 0;
  END IF;

  IF configured_capacity IS NULL OR configured_capacity <= 0 THEN
    RAISE EXCEPTION 'Total capacity must be greater than zero';
  END IF;

  SELECT COUNT(*)
  INTO slot_count
  FROM public.list_ticket_time_slots(p_ticket_id);

  IF slot_count = 0 THEN
    RAISE EXCEPTION 'Ticket % has no time slots configured', p_ticket_id;
  END IF;

  WITH days AS (
    SELECT generate_series(effective_start_date, effective_end_date, INTERVAL '1 day')::DATE AS service_date
  ),
  slots AS (
    SELECT time_slot FROM public.list_ticket_time_slots(p_ticket_id)
  ),
  inserted AS (
    INSERT INTO public.ticket_availabilities (
      ticket_id,
      date,
      time_slot,
      total_capacity,
      reserved_capacity,
      sold_capacity,
      version,
      created_at,
      updated_at
    )
    SELECT
      p_ticket_id,
      d.service_date,
      s.time_slot,
      configured_capacity,
      0,
      0,
      0,
      NOW(),
      NOW()
    FROM days d
    CROSS JOIN slots s
    ON CONFLICT (ticket_id, date, time_slot) DO NOTHING
    RETURNING 1
  )
  SELECT COUNT(*)
  INTO inserted_count
  FROM inserted;

  RETURN inserted_count;
END;
$$;
CREATE OR REPLACE FUNCTION public.regenerate_ticket_availability(
  p_start_date DATE,
  p_end_date DATE,
  p_ticket_id BIGINT DEFAULT 1,
  p_total_capacity INTEGER DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  effective_start_date DATE;
  effective_end_date DATE;
  configured_capacity INTEGER;
  slot_times TIME[];
  inserted_count INTEGER := 0;
  updated_count INTEGER := 0;
  deleted_count INTEGER := 0;
  skipped_locked_count INTEGER := 0;
BEGIN
  IF p_start_date IS NULL OR p_end_date IS NULL THEN
    RAISE EXCEPTION 'Start date and end date are required';
  END IF;

  IF p_start_date > p_end_date THEN
    RAISE EXCEPTION 'Start date must be before or equal to end date';
  END IF;

  IF auth.uid() IS NOT NULL AND NOT public.is_admin() THEN
    RAISE EXCEPTION 'Only admins can regenerate ticket availability';
  END IF;

  SELECT
    GREATEST(p_start_date, t.available_from::DATE),
    LEAST(p_end_date, t.available_until::DATE),
    COALESCE(p_total_capacity, s.default_slot_capacity)
  INTO
    effective_start_date,
    effective_end_date,
    configured_capacity
  FROM public.tickets t
  JOIN public.ticket_booking_settings s ON s.ticket_id = t.id
  WHERE t.id = p_ticket_id;

  IF effective_start_date IS NULL OR effective_end_date IS NULL OR effective_start_date > effective_end_date THEN
    RETURN jsonb_build_object(
      'inserted', 0,
      'updated', 0,
      'deleted', 0,
      'skipped_locked', 0
    );
  END IF;

  SELECT ARRAY_AGG(time_slot ORDER BY time_slot)
  INTO slot_times
  FROM public.list_ticket_time_slots(p_ticket_id);

  IF slot_times IS NULL OR array_length(slot_times, 1) IS NULL THEN
    RAISE EXCEPTION 'Ticket % has no time slots configured', p_ticket_id;
  END IF;

  WITH days AS (
    SELECT generate_series(effective_start_date, effective_end_date, INTERVAL '1 day')::DATE AS service_date
  ),
  desired AS (
    SELECT d.service_date, slot_time AS time_slot
    FROM days d
    CROSS JOIN unnest(slot_times) AS slot_time
  ),
  inserted AS (
    INSERT INTO public.ticket_availabilities (
      ticket_id,
      date,
      time_slot,
      total_capacity,
      reserved_capacity,
      sold_capacity,
      version,
      created_at,
      updated_at
    )
    SELECT
      p_ticket_id,
      desired.service_date,
      desired.time_slot,
      configured_capacity,
      0,
      0,
      0,
      NOW(),
      NOW()
    FROM desired
    LEFT JOIN public.ticket_availabilities ta
      ON ta.ticket_id = p_ticket_id
     AND ta.date = desired.service_date
     AND ta.time_slot = desired.time_slot
    WHERE ta.id IS NULL
    RETURNING 1
  ),
  updated AS (
    UPDATE public.ticket_availabilities ta
    SET
      total_capacity = configured_capacity,
      updated_at = NOW()
    FROM desired
    WHERE ta.ticket_id = p_ticket_id
      AND ta.date = desired.service_date
      AND ta.time_slot = desired.time_slot
      AND ta.reserved_capacity = 0
      AND ta.sold_capacity = 0
      AND ta.total_capacity <> configured_capacity
    RETURNING ta.id
  ),
  deleted AS (
    DELETE FROM public.ticket_availabilities ta
    WHERE ta.ticket_id = p_ticket_id
      AND ta.date BETWEEN effective_start_date AND effective_end_date
      AND ta.time_slot IS NOT NULL
      AND ta.reserved_capacity = 0
      AND ta.sold_capacity = 0
      AND NOT EXISTS (
        SELECT 1
        FROM unnest(slot_times) AS desired_slot
        WHERE desired_slot = ta.time_slot
      )
    RETURNING ta.id
  ),
  locked AS (
    SELECT ta.id
    FROM public.ticket_availabilities ta
    WHERE ta.ticket_id = p_ticket_id
      AND ta.date BETWEEN effective_start_date AND effective_end_date
      AND (
        (ta.time_slot = ANY(slot_times) AND (ta.reserved_capacity > 0 OR ta.sold_capacity > 0))
        OR (
          ta.time_slot IS NOT NULL
          AND NOT (ta.time_slot = ANY(slot_times))
          AND (ta.reserved_capacity > 0 OR ta.sold_capacity > 0)
        )
      )
  )
  SELECT
    (SELECT COUNT(*) FROM inserted),
    (SELECT COUNT(*) FROM updated),
    (SELECT COUNT(*) FROM deleted),
    (SELECT COUNT(*) FROM locked)
  INTO
    inserted_count,
    updated_count,
    deleted_count,
    skipped_locked_count;

  RETURN jsonb_build_object(
    'inserted', inserted_count,
    'updated', updated_count,
    'deleted', deleted_count,
    'skipped_locked', skipped_locked_count
  );
END;
$$;
CREATE OR REPLACE FUNCTION public.ensure_ticket_availability_coverage(
  p_ticket_id BIGINT DEFAULT 1,
  p_days_ahead INTEGER DEFAULT NULL,
  p_total_capacity INTEGER DEFAULT NULL
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  configured_days_ahead INTEGER;
BEGIN
  SELECT COALESCE(p_days_ahead, s.auto_generate_days_ahead)
  INTO configured_days_ahead
  FROM public.ticket_booking_settings s
  WHERE s.ticket_id = p_ticket_id;

  IF configured_days_ahead IS NULL OR configured_days_ahead <= 0 THEN
    RETURN 0;
  END IF;

  RETURN public.generate_ticket_availability(
    CURRENT_DATE,
    CURRENT_DATE + configured_days_ahead,
    p_ticket_id,
    p_total_capacity
  );
END;
$$;
CREATE OR REPLACE FUNCTION public.ensure_all_ticket_availability_coverage()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  total_inserted INTEGER := 0;
  ticket_row RECORD;
BEGIN
  FOR ticket_row IN
    SELECT s.ticket_id, s.auto_generate_days_ahead, s.default_slot_capacity
    FROM public.ticket_booking_settings s
    WHERE s.auto_generate_days_ahead > 0
  LOOP
    total_inserted := total_inserted + public.ensure_ticket_availability_coverage(
      ticket_row.ticket_id,
      ticket_row.auto_generate_days_ahead,
      ticket_row.default_slot_capacity
    );
  END LOOP;

  RETURN total_inserted;
END;
$$;
GRANT EXECUTE ON FUNCTION public.generate_ticket_availability(DATE, DATE, BIGINT, INTEGER) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.regenerate_ticket_availability(DATE, DATE, BIGINT, INTEGER) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ensure_ticket_availability_coverage(BIGINT, INTEGER, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.ensure_all_ticket_availability_coverage() TO service_role;
CREATE OR REPLACE FUNCTION public.reserve_ticket_capacity(
  p_ticket_id BIGINT,
  p_date DATE,
  p_time_slot TEXT,
  p_quantity INTEGER
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_quantity IS NULL OR p_quantity <= 0 THEN
    RETURN false;
  END IF;

  WITH target AS (
    SELECT
      ta.id,
      ta.reserved_capacity,
      ta.sold_capacity,
      COALESCE(so.capacity_override, dlo.capacity_override, ta.total_capacity) AS effective_total_capacity,
      COALESCE(so.is_closed, dlo.is_closed, false) AS is_closed
    FROM public.ticket_availabilities ta
    LEFT JOIN public.ticket_availability_overrides so
      ON so.ticket_id = ta.ticket_id
     AND so.date = ta.date
     AND so.time_slot = ta.time_slot
    LEFT JOIN public.ticket_availability_overrides dlo
      ON dlo.ticket_id = ta.ticket_id
     AND dlo.date = ta.date
     AND dlo.time_slot IS NULL
    WHERE ta.ticket_id = p_ticket_id
      AND ta.date = p_date
      AND ta.time_slot IS NOT DISTINCT FROM (p_time_slot::TIME)
    FOR UPDATE
  )
  UPDATE public.ticket_availabilities ta
  SET
    reserved_capacity = ta.reserved_capacity + p_quantity,
    updated_at = NOW()
  FROM target
  WHERE ta.id = target.id
    AND target.is_closed = false
    AND (target.effective_total_capacity - target.reserved_capacity - target.sold_capacity) >= p_quantity;

  RETURN FOUND;
END;
$$;
DO $$
DECLARE
  existing_job_id BIGINT;
BEGIN
  SELECT jobid
  INTO existing_job_id
  FROM cron.job
  WHERE jobname = 'ensure-ticket-availability-daily';

  IF existing_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(existing_job_id);
  END IF;

  PERFORM cron.schedule(
    'ensure-ticket-availability-daily',
    '15 17 * * *',
    $cron$SELECT public.ensure_all_ticket_availability_coverage();$cron$
  );
END;
$$;
